spring:
  application:
    name: interview
  datasource:
    url: jdbc:sqlserver://192.168.1.68:1433;databaseName=msvc_interview;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 2020640576
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    com.zaxxer.hikari: DEBUG
server:
  port: 8084