spring:
  application:
    name: interview
  datasource:
    url: jdbc:sqlserver://192.168.1.68:1433;databaseName=msvc_interview;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 2020640576
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    com.zaxxer.hikari: DEBUG
server:
  port: 8084
eureka:
  instance:
    ip-address: 158.23.81.1
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.1:8761/eureka